[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    parent = "work"
    weight = 2

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "work"
    weight = 1

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "work"
    weight = 3

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 4

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    parent = "writing"
    weight = 4

[[main]]
    identifier = "reinforce"
    name = "Reinforcement Learning"
    # url = "/reinforce/"
    url = "/posts/reinforce/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5

[[main]]
    identifier = "ssl"
    name = "Self/Semi-Supervised Learning"
    # url = "/ssl/"
    url = "/posts/ssl/" # Remove url param from subsection2/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 6

[[main]]
    identifier = "notes"
    name = "Other Notes"
    # url = "/subsection3/"
    url = "/posts/notes/" # Remove url param from subsection3/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 7

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8

[[main]]
    identifier = "project-type"
    name = "Project Types"
    url = "/project-types/"
    parent = "explore"
    weight = 9

[[main]]
    # Top-level menu entry
    identifier = "other"
    name = "Other Sites"
    url = "/categories/"
    weight = 7

[[main]]
    identifier = "homepage"
    name = "Homepage - FF"
    url = "/categories/"
    parent = "other"
    weight = 7

[[main]]
    identifier = "myblog"
    name = "Personal Blog"
    url = "https://flammingfrost.github.io/my-blog/"
    parent = "other"
    weight = 8

[[main]]
    identifier = "github"
    name = "Github - FlammingFrost"
    url = "https://github.com/FlammingFrost"
    parent = "other"
    weight = 9
